# Generated by Django 4.2 on 2023-04-25 08:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="session_URL",
            new_name="session_url",
        ),
    ]
