# Generated by Django 4.2 on 2023-04-26 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"default_related_name": "payments"},
        ),
    ]
