# Generated by Django 4.2 on 2023-04-26 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment_service", "0002_rename_session_url_payment_session_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"default_related_name": "payments"},
        ),
    ]
